# Generated by Django 4.2.6 on 2023-12-13 10:30

import Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(db_column='Department_ID', primary_key=True, serialize=False)),
                ('dep_name', models.CharField(blank=True, db_column='Dep_Name', max_length=40, null=True)),
            ],
            options={
                'db_table': 'Department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(db_column='Designation_ID', primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, db_column='Designation', max_length=50, null=True)),
                ('dep', models.ForeignKey(blank=True, db_column='Dep_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.department')),
            ],
            options={
                'db_table': 'Designation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('manager_id', models.AutoField(db_column='Manager_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Managers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('emp_id', models.CharField(db_column='Emp_ID', max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('email', models.CharField(db_column='email', default='anu@mail.com', max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('date_of_joining', models.DateField(blank=True, db_column='Date_of_Joining', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='Updated_at', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='Created_at', null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('balance', models.IntegerField(blank=True, db_column='Balance', null=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, db_column='Department_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.department')),
                ('designation', models.ForeignKey(blank=True, db_column='desig_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.designation')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('managed_by', models.ForeignKey(blank=True, db_column='Managed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.managers')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Employees',
                'managed': True,
            },
            managers=[
                ('objects', Users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='managers',
            name='emp',
            field=models.ForeignKey(blank=True, db_column='EMP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
